name: Docker Image CI


on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mkv-language-remover

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Tag
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" = "dev" ]; then
          echo "IMAGE_TAG=dev" >> $GITHUB_ENV
        fi



    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ env.IMAGE_TAG }}

    - name: Push to Docker Hub
      run: docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}

